"""Generate docs/prompts.md from the prompts that actually run.

The prompt documentation is a submission requirement, and a prompt document
that has drifted from the code is worse than none. This reads
`backend/llm/prompts.py` and writes the document, so the two cannot disagree.

    python scripts/generate_prompt_docs.py
"""

import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT))

from backend.llm.prompts import (  # noqa: E402
    CONFLICT_EXPLANATION_PROMPT,
    EXPLANATION_PROMPT,
    INTENT_EXTRACTION_PROMPT,
    SYSTEM_PROMPT,
    VISION_SYSTEM_PROMPT,
)

HEADER = """# KOHLER AI BathPlan — Prompt Documentation

> **Generated from `backend/llm/prompts.py` by `scripts/generate_prompt_docs.py`.**
> Do not edit this file by hand. Every prompt below is the exact text the running
> system sends — regenerating is how it stays true.

---

## The design principle

This system is built on one architectural commitment:

> **The language model is not the source of truth.**

Dimensions, prices, physical feasibility, compatibility, installation
requirements and water calculations are all computed by deterministic code
*before* any model is called. The model receives those results as given facts.
It cannot change them, and it is never asked to produce them.

That is why the prompts below are narrow. Each one has a single job, a
structured output schema, and an explicit list of things it is forbidden to
assert. A model that hallucinates inside this system produces a *malformed
request*, which validation rejects — not a wrong answer that reaches the user.

### What the model is allowed to do

| Responsibility | Why the model |
|---|---|
| Interpret a sentence into a structured request | Language understanding is genuinely what it is good at |
| Explain a computed result in plain language | Turning structured data into readable prose |
| Describe trade-offs already identified by the engines | Same |

### What the model is never allowed to do

| Forbidden | Who does it instead |
|---|---|
| Decide whether a fixture fits | `backend/layout/solver.py` — geometry and code clearances |
| State a dimension, price or flow rate | `catalog/products.json`, read directly |
| Declare a configuration feasible | `backend/constraints/engine.py` |
| Calculate water use | `backend/sustainability/calculator.py` |
| Rank configurations | `backend/recommendation/engine.py` |
| Convert an unknown into an assumption | Nobody. Unknown stays unknown. |

### Enforcement is structural, not by instruction

Telling a model not to invent things is necessary but not sufficient. The
guardrails that actually hold are in code:

- **Vision output** is typed with `authoritative: Literal[False]`. The schema has
  no field for a dimension, a rough-in, or an electrical fact, so vision output
  *cannot* reach the constraint engine even if the model tried.
- **Intent output** is sanitised against a fixed category vocabulary
  (`ModificationIntent.sanitised()`). An invented category is dropped before it
  reaches the pipeline.
- **Every model call is wrapped.** A timeout, a network failure or malformed JSON
  falls back to the deterministic path, which is capable enough to run the whole
  product alone.
- **`computed_by`** on every response names the engine behind each figure. `"llm"`
  never appears in it.

---

"""

FOOTER = """---

## Fallback behaviour

Every prompt here is optional. With no API key configured:

| Capability | Fallback | Quality |
|---|---|---|
| Intent extraction | `extract_intent_keywords()` — clause-splitting keyword parser | Handles every phrase in the demo script, plus add/remove in one sentence, verbless clause inheritance, priority shifts, questions, and Indian budget formats (lakh / crore / Rs) |
| Explanation | `build_explanation()` — templated from structured results | Complete and accurate; plainer prose |
| Vision | Manual dimension entry | Full planning; no photo context |

The product is fully usable in this mode. This is not a degraded demo path — it
is the tested default, and the entire 130-test suite runs against it.

---

## Why the LLM's responsibility is bounded

The honest argument for this design is that the failure modes are asymmetric.

A language model that misreads "add a smart shower but keep my budget" produces a
request that the constraint engine then evaluates — and if the result breaks the
budget, the user sees a conflict with options. The error is *contained and
visible*.

A language model asked to decide whether a 72-inch vanity fits a 5-foot wall
produces a confident sentence with no way for the user to tell it is wrong. The
error is *invisible and actionable* — someone might buy the vanity.

So the model does the first job and never the second. This is also why the
product's most important screen is the one where it says no.
"""


def section(number: int, title: str, purpose: str, output: str, forbidden: list[str], prompt: str) -> str:
    lines = [
        f"## {number}. {title}",
        "",
        f"**Purpose.** {purpose}",
        "",
        f"**Structured output.** {output}",
        "",
        "**Explicitly forbidden from producing:**",
        "",
    ]
    lines.extend(f"- {item}" for item in forbidden)
    lines.extend(["", "**Exact prompt text:**", "", "```text", prompt.strip(), "```", "", "---", ""])
    return "\n".join(lines)


def build() -> str:
    parts = [HEADER]

    parts.append(
        section(
            1,
            "System prompt",
            "Sets the model's role and boundaries for every conversational call. "
            "Prepended as the system instruction on intent extraction and explanation.",
            "None directly — this frames the calls below.",
            [
                "Any dimension, price, flow rate or water figure not supplied to it",
                "A feasibility verdict of any kind",
                "An invented KOHLER product, model number or specification",
                "An assumption substituted for an unverified measurement",
            ],
            SYSTEM_PROMPT,
        )
    )

    parts.append(
        section(
            2,
            "Intent extraction",
            "Converts a plain-language modification request into a structured change. "
            "This is translation, not planning — the engines evaluate the result and will "
            "reject it if it cannot be built.",
            "`ModificationIntent` — add/remove categories, budget change, priority shift, "
            "preferred styles, question, summary. Validated by Pydantic; unknown category "
            "names are stripped by `sanitised()`.",
            [
                "Any category outside the fixed vocabulary of nine",
                "A judgement about whether the request is achievable",
                "A budget figure the user did not state",
            ],
            INTENT_EXTRACTION_PROMPT,
        )
    )

    parts.append(
        section(
            3,
            "Result explanation",
            "Rewrites an already-computed configuration into readable prose. Used only to "
            "improve wording — `build_explanation()` has already produced a complete, "
            "accurate version from the structured result.",
            "Free text, 2–4 sentences. Replaces nothing; the structured data is what the UI "
            "renders alongside it.",
            [
                "Any figure not present in the computed result",
                "Softening a verification requirement into a reassurance",
                "Marketing language ('perfect', 'ideal', 'dream bathroom')",
            ],
            EXPLANATION_PROMPT,
        )
    )

    parts.append(
        section(
            4,
            "Conflict explanation",
            "Explains why no configuration satisfied every requirement, and presents the "
            "relaxations the engine actually evaluated.",
            "Free text. The relaxation list itself comes from "
            "`_suggest_relaxations()` and is rendered as structured, clickable choices.",
            [
                "A workaround the engine did not evaluate",
                "Choosing which constraint should give way — that is the user's decision",
                "Implying the conflict is smaller than the computed figures show",
            ],
            CONFLICT_EXPLANATION_PROMPT,
        )
    )

    parts.append(
        section(
            5,
            "Vision analysis",
            "Extracts conservative spatial evidence from a single bathroom photograph. "
            "Advisory context only — this output never reaches the constraint engine.",
            "`BathroomVisionEvidence` — detected objects with confidence, approximate zones, "
            "ambiguities, occlusions, and a mandatory `unverifiable_attributes` block. "
            "`authoritative` is typed `Literal[False]` and is re-set server-side after "
            "validation; `overall_confidence` is recomputed server-side rather than trusted.",
            [
                "Room dimensions — a single photograph cannot establish them",
                "Toilet rough-in, hidden piping or wall structure",
                "Electrical availability",
                "Treating a fixture seen only in a mirror reflection as a real fixture",
                "Any layout recommendation or structural guarantee",
            ],
            VISION_SYSTEM_PROMPT,
        )
    )

    parts.append(FOOTER)
    return "\n".join(parts)


def main() -> int:
    target = REPO_ROOT / "docs" / "prompts.md"
    target.write_text(build(), encoding="utf-8")
    print(f"Wrote {target.relative_to(REPO_ROOT)} ({target.stat().st_size:,} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
